In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([1,2,3,4,5], dtype = 'float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [4]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
x = np.random.randint(10 , size = (3,4))
x

array([[9, 3, 5, 3],
       [7, 5, 3, 3],
       [3, 6, 5, 4]])

In [6]:
x[:2,:3] # Accessing two rows and three columns

array([[9, 3, 5],
       [7, 5, 3]])

In [7]:
x[:3,:2] # Accessing 3 rows and 2 columns

array([[9, 3],
       [7, 5],
       [3, 6]])

In [8]:
x[:,0]  # First Column of X

array([9, 7, 3])

In [9]:
x[0,:]  # First Row of X

array([9, 3, 5, 3])

In [10]:
x


array([[9, 3, 5, 3],
       [7, 5, 3, 3],
       [3, 6, 5, 4]])

In [11]:
x[0,2] = 7
x

array([[9, 3, 7, 3],
       [7, 5, 3, 3],
       [3, 6, 5, 4]])

The Copy() method copies the array but modifiying the copy wont affect the original

In [12]:
x_copy = x.copy()
x_copy

array([[9, 3, 7, 3],
       [7, 5, 3, 3],
       [3, 6, 5, 4]])

In [13]:
x_copy[0,1] = 10
x_copy

array([[ 9, 10,  7,  3],
       [ 7,  5,  3,  3],
       [ 3,  6,  5,  4]])

In [14]:
x

array([[9, 3, 7, 3],
       [7, 5, 3, 3],
       [3, 6, 5, 4]])